### PR TITLE
Added phase 4 capstone project

### PR DESCRIPTION
**Pull request by rishabkumar7**
Added the Capstone Project for Phase 4: QR Code Generator

### CODE REVIEW

**Review by madebygps — CHANGES_REQUESTED** [review]
We discussed providing the source code of the app so learners can focus on devops practices for the capstone. Can we do that? 

Also please feel free to remove the projects section.

**Comment by rishabkumar7** [comment]
@madebygps Sure I include the repo, for the code, should it be just the logic right, we let learners figure out how the containers will talk to each other and how the SDK will be implemented?

**Comment by madebygps** [comment]
Yes. Their job is to containarize and deploy. Cicd and monitoring if possible too. Maybe have them setup a simple monitoring alert?

**Review by madebygps — APPROVED** [review]
lgtm, approved.

**Pull request merged**
