### PR TITLE
Phase 5 translated to brazilian portuguese

### PR DESCRIPTION
**Pull request by ViniViniAntunes**

### CODE REVIEW

**Review by rishabkumar7 — COMMENTED** [review]
@ViniViniAntunes Could you change the sidebar links to point at `/pt/phase/README`, otherwise you are directed to English verison

**Review by rishabkumar7 — CHANGES_REQUESTED** [review]
@ViniViniAntunes I am not sure if you saw my last comment, in the _sidebar.md we need to point each phase to `pt/phaseX/README.md' and not `phaseX/README.md'

**Comment by ViniViniAntunes** [comment]
> @ViniViniAntunes I am not sure if you saw my last comment, in the _sidebar.md we need to point each phase to `pt/phaseX/README.md' and not `phaseX/README.md'

@rishabkumar7 , with `pt/phaseX/README.md` the links not work. With `phaseX/README.md` they work correctly because they are inside `pt` folder already.

**Comment by rishabkumar7** [comment]
> > @ViniViniAntunes I am not sure if you saw my last comment, in the _sidebar.md we need to point each phase to `pt/phaseX/README.md' and not `phaseX/README.md'
> 
> @rishabkumar7 , with `pt/phaseX/README.md` the links not work. With `phaseX/README.md` they work correctly because they are inside `pt` folder already.

@ViniViniAntunes Ah I see, you have a _sidebar.md inside the pt folder, makes sense, my bad!

**Comment by ViniViniAntunes** [comment]
> 
> @ViniViniAntunes Ah I see, you have a _sidebar.md inside the pt folder, makes sense, my bad!

No problem! I made like the franch version that it is working. It was my exemple

**Pull request merged**
