### PR TITLE
Hacktoberfest 

### PR DESCRIPTION
**Pull request by faizanlalcode**

### CODE REVIEW

**Comment by faizanlalcode** [comment]
great

**Comment by faizanlalcode** [comment]
happy

**Comment by faizanlalcode** [comment]
ok

**Comment by faizanlalcode** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Twitter Hovercard</title>
    <link rel="stylesheet" href="./twitterstyle.css" />
  </head>
  <body>
    <div class="container">
      <div class="card">
        <div class="profile">
          <div class="main-profile"></div>
          <div class="user-bio"></div>
          <div class="user-follows"></div>

          <div class="main-profile">
            <div class="user-info">
              Profile Pic
              <h3>Faizan</h3>
              <p>@faizancode</p>
            </div>
            <div class="follow-btn">
              <button>Follow</button>

            </div>
        </div>
        <div class="user-bio">
          <p>
             Programmer
            <br />
             18 years old
            <br />
            My name is Faizan
            
            
          </p>
        </div>
  
        <div class="user-follows">
          <div><b>16</b> Following</div>
          <div><b>10</b> Followers</div>
        </div>
            </div>
          </div>
          
        </div>
      </div>
      <div class="user-bio">
        <p>
           Programmer
          <br />
           18 years old
          <br />
          My name is Faizan
          
          
        </p>
      </div>

      <div class="user-follows">
        <div><b>16</b> Following</div>
        <div><b>10</b> Followers</div>
      </div>
      
      
    </div>
  </body>
</html>

**Comment by madebygps** [comment]
LTC contributors is updated automatically when someone adds something to the guide. If you would like to contribute, please add a resource, a task in a phase, or a project in the projects page.

**Review by madebygps — COMMENTED** [review]
LTC contributors is updated automatically when someone adds something to the guide. If you would like to contribute, please add a resource, a task in a phase, or a project in the projects page.

**Pull request closed without merging**
