### PR TITLE
Apprendre le Cloud 

### PR DESCRIPTION
**Pull request by verlaine-muhungu**
French version of the learn to cloud,translated by Abdennour and verlaine

### CODE REVIEW

**Comment by rishabkumar7** [comment]
I think all these changes are to existing readmes, which is the english version of the guide and we need it, in order to add French language support, this needs to be done:
For the language support, you will have to create a different directory, I would suggest it under the root.
```
    └── fr
        ├── README.md
        ├── _sidebar.md
```

**Comment by madebygps** [comment]
Hi all, have you been able to look at the suggestions from Rishab on how to implement this?

**Comment by verlaine-muhungu** [comment]
> 
Hello gwyn i think the implementation was not clear to me,your help will be appreciated how to implement the solution step by step,then we will translate the fifth Phase

**Comment by rishabkumar7** [comment]
@verlaine-muhungu  so basically we need a new directory (folder) under the root directory to hold all the `readme` files with french translations, instead of updating the existing ones, let me know if it makes sense.

**Comment by verlaine-muhungu** [comment]
> @verlaine-muhungu so basically we need a new directory (folder) under the root directory to hold all the `readme` files with french translations, instead of updating the existing ones, let me know if it makes sense.

should i do it with MY ubuntu CLI ?

**Pull request merged**
