### PR TITLE
Random cloud term api implementation to the homepage

### PR DESCRIPTION
**Pull request by rishabkumar7**
Added the Random Cloud term api to the homepage:
- API Component
- CSS changes to the homepage

### CODE REVIEW

**Comment by rishabkumar7** [comment]
Checks passed cool 👍🏽

**Comment by madebygps** [comment]
@rishabkumar7 Preview doesn't re-generate when new commits are added... I can't tell if new URL and title updates work.

**Comment by rishabkumar7** [comment]
@madebygps here's how it looks
image

**Comment by madebygps** [comment]
looks good

**Pull request merged**
