### PR TITLE
Issue 120 spanish translation

### PR DESCRIPTION
**Pull request by azgcloudev**
- remove old es directory, it included old ltc format
- created the spanish folder and add and complete phase 0

### CODE REVIEW

**Review by madebygps — COMMENTED** [review]
@rishabkumar7 translation is good but is it okay that those files were deleted?

**Comment by rishabkumar7** [comment]
@madebygps still waiting on the reply on to why `welcome.md` was deleted?

**Comment by azgcloudev** [comment]
@madebygps I deleted the old ones because did not had the phases format

@rishabkumar7 I just noticed I missed the welcome, let me add it today

**Comment by rishabkumar7** [comment]
thanks @azgcloudev !

**Comment by azgcloudev** [comment]
@rishabkumar7 I added the `welcome.md` page again

**Comment by madebygps** [comment]
@rishabkumar7 I think this is good to merge now?

**Comment by rishabkumar7** [comment]
lgtm ✅

**Review by rishabkumar7 — COMMENTED** [review]
lgtm

**Pull request merged**
